---
- name: Pull Docker Image
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Copy from host machine to remote host
      copy:
        src: ./
        dest: ./app
    - name: Pull the Docker images specifed in docker-compose
      shell: 
        cmd: docker-compose pull
        chdir: ./app
    - name: Running container
      shell: 
        cmd: docker-compose -f ./docker-compose.yml up -d
        chdir: ./app

